# frozen_string_literal: true

require "bundler/gem_tasks"
require "fileutils"
require "rake/extensiontask"
require "rspec/core/rake_task"

Rake::ExtensionTask.new("userfaultfd") do |ext|
  ext.lib_dir = "lib/userfaultfd"
end

RSpec::Core::RakeTask.new(:spec) do |task|
  task.pattern = "spec/**/*_spec.rb"
end

namespace :test do
  RSpec::Core::RakeTask.new(:unit) do |task|
    task.pattern = "spec/unit/**/*_spec.rb"
  end

  RSpec::Core::RakeTask.new(:system) do |task|
    task.pattern = "spec/system/**/*_spec.rb"
  end
end

task spec: :compile

namespace :gen do
  desc "Generate C constant bindings from the installed Linux headers"
  task :constants do
    executable = "tmp/dump_userfaultfd_constants"
    FileUtils.mkdir_p("tmp")
    sh "#{RbConfig::CONFIG.fetch("CC")} -Iext/userfaultfd tools/dump_constants.c -o #{executable}"
    names = IO.popen(executable, &:read).lines.map { |line| line.split("=", 2).first }
    body = names.map { |name| "#ifdef #{name}\n    UFFD_CONST(#{name});\n#endif" }.join("\n")
    File.write("ext/userfaultfd/constants.c", <<~C)
      /* Generated by rake gen:constants. Do not edit. */
      #include "ruby.h"
      #ifdef __linux__
      # include "compat.h"
      # define UFFD_CONST(name) rb_define_const(klass, #name, ULL2NUM(name))
      #else
      # define UFFD_CONST(name) ((void)0)
      #endif
      void userfaultfd_define_constants(VALUE klass)
      {
      #{body}
      }
    C
  end
end

task default: :spec
