# frozen_string_literal: true

require_relative "userfaultfd/version"

class UserfaultFD
  class Error < StandardError; end
  class UnsupportedError < Error; end
  class DeadlockError < Error; end

  class << self
    attr_accessor :strict
  end

  self.strict = false
end

require "userfaultfd/userfaultfd"
require_relative "userfaultfd/handler"

class UserfaultFD
  def to_io
    IO.for_fd(fileno, autoclose: false)
  end

  def start_handler(mode: nil, io: nil, source: nil, &block)
    Handler.new(self, mode: mode, io: io, source: source, &block)
  end
end

class UserfaultFD::Fault
  def write? = flags.include?(:write)
  def wp? = flags.include?(:wp)
  def minor? = flags.include?(:minor)
end

# Compatibility with the constant generated by the original gem skeleton.
Userfaultfd = UserfaultFD
