name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'
          - '4.0'

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Compile and run unit tests
        run: bundle exec rake compile test:unit
      - name: Validate RBS
        run: bundle exec rbs -I sig validate
      - name: Build gem
        run: bundle exec gem build userfaultfd.gemspec

  system:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Run host-kernel tests
        run: bundle exec rake compile test:system
